### ISSUE TITLE
Get actual design

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#10]
Hire someone.

**Comment by wlonk** [comment]
This should include setting `og` tags.

**Comment by wlonk** [comment]
Via Nick:

> I made a profile there. It seems to display funny when I have an odd number of entries. When I have 5 or 7 entries, the middle one gets cut in half, with part displayed on the bottom of the left column and half on the top of the right column.

> EDIT: That's the behavior in Chrome, anyway. In Microsoft Edge, I get something similar, but only a small sliver is cut off. In Firefox, it displays fine.

**Comment by ojacobson** [comment]
It displayed fine in Safari, too, before you removed it. I'm skeptical of Bootstrap's overall portability, here.

**Comment by ojacobson** [comment]
I really liked your observation that each individal social media identity is somewhat like a tiny business card/moocard.

**Comment by wlonk** [comment]
Temporarily closed by #69.
