### ISSUE TITLE
Integrate with Keybase

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#111]
Per https://keybase.io/docs/proof_integration_guide

**Comment by wlonk** [comment]
Since Keybase is now owned by Zoom, I'm much less enthusiastic about this, but Nelson suggested https://keys.pub/docs/ instead. Maybe?

**Comment by kahomono** [comment]
Help me out here: Why does the Zoom acquisition reduce your interest in Keybase?  

https://keys.pub appears to be a few orders of magnitude less-used.

**Comment by wlonk** [comment]
Zoom has a track record of what amount to MitM attacks on their users; there's a chance of them supply-chain attacking Keybase and undermining the whole idea.

I agree; keys.pub doesn't do the same thing and doesn't have much uptake, I just wanted to write down the suggestion here where I'd find it whenever I get a chance to work on this ticket.

**Comment by kahomono** [comment]
To do so would undermine the whole value of their investment unless they could keep it completely secret.  And I think they know that will not work.

**Comment by wlonk** [comment]
I certainly wouldn't reject out of hand a patch to add this feature! I'm just not going to prioritize this effort myself.
