### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by PrinterElf** [wlonk/wheretofind.me#116]
Would be nice to see the following icons if possible.
Adding one per comment to this issue so that likes (<img src="https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png" width="16">) can be used to indicate preference.

**Comment by PrinterElf** [comment]
Telegram:
<img src="https://upload.wikimedia.org/wikipedia/commons/8/82/Telegram_logo.svg" width="64">

**Comment by PrinterElf** [comment]
LinkedIn:
<img src="https://upload.wikimedia.org/wikipedia/commons/c/ca/LinkedIn_logo_initials.png" width="64">

**Comment by wlonk** [comment]
@PrinterElf Thanks! I use the icons from Fontawesome, which saves me design time and ensures that they're all styled consistently without me having to wade through brand-use requirements for each service. It looks like Fontawesome has both of these, so I'll add them now. I appreciate the feedback!
