### ISSUE TITLE
Would be really really nice to have an "information saved" indicator on the locations adding page

### ISSUE THREAD

**Issue by toBeOfUse** [wlonk/wheretofind.me#125]
If I can't see any indication that the information I've put in is saved, I can't leave a page without having a nervous breakdown. This may be unique to me, but I doubt it. This is kind of justified, even, because if you're going quickly and you type in a name and a url and close the tab or refresh or navigate to a different page with the url field still in focus, the url won't be saved, because apparently form data isn't uploaded until the relevant form element loses focus. The simplest way to fix that specific problem would be to add a `beforeunload` event listener that uploads the currently focused field's contents to the server when the page is left; that doesn't help inform one that they can leave the page without losing anything, though.

One wild idea would be to add a dummied-out "save" button to the bottom of the page to both display a reassuring indicator on command and to prompt the user to shift focus to something other than the form; put a spinner beside it that displays as a checkmark when/if all info upload requests are done. Otherwise, I'm not sure how to show an indicator that accurately shows whether changes are saved with an autosave model driven by these events.

**Comment by wlonk** [comment]
Excellent idea!

**Comment by toBeOfUse** [comment]
Wow, that was fast

**Comment by wlonk** [comment]
Well, let's see how fast I am at actually implementing this change.

**Comment by toBeOfUse** [comment]
#128 was merged and accomplished this
