### ISSUE TITLE
Making a change to a location and then hitting the enter key sends the update request twice

### ISSUE THREAD

**Issue by toBeOfUse** [wlonk/wheretofind.me#130]
Not really a "problem" per se but certainly an interesting quirk. Looks like listening for the enter key, which the Identity components' fields do, is unnecessary, as hitting it also triggers a "change" event for the field to pick up on.

**Comment by wlonk** [comment]
I'm gonna triage this into "won't fix" for now; we aren't facing issues with API load that would make this worth fixing. The UI is designed with the intent that it should hit the API more often than not to ensure everything is saved as much as possible. If we need to revisit this, we can!
