### ISSUE TITLE
Update to Django 3

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#138]
Just keeping up with dependencies.

**Comment by ojacobson** [comment]
Looking at the [release notes](https://docs.djangoproject.com/en/3.0/releases/3.0/), I'm surprised to discover that I _don't_ particularly disagree with the "good first issue" tag on this. It looks like the major-version-sized feature is full async support, but it's _support_, not _migration_, and it's something we could tackle separately if and when we need it, independent of upgrading Django.

**Comment by wlonk** [comment]
Yup!
