### ISSUE TITLE
Bug: "fa-keybase" doesn't cause Keybase icon to show up

### ISSUE THREAD

**Issue by elimisteve** [wlonk/wheretofind.me#153]
Cause: ForkAwesome overrides the `fa-keybase` definition from `\f4f5` (which is correct) to `\f2f4` (which is not).

Maybe there's a newer version of ForkAwesome that doesn't try to add `fa-keybase` since it's now been added to upstream?

**Comment by wlonk** [comment]
Uff. I'll look into this.
