### ISSUE TITLE
Make icons selectable

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#17]
Icons shouldn't be guessed from the URL, they should be user-set, though a first-guess should come from the URL and be automatic.

**Comment by ojacobson** [comment]
> While you're at it, can you add a ticket for me to put down an exhaustive list of service icons?

**Comment by ojacobson** [comment]
It might additionally be worth trying to detect off the name field: `mastodon` includes sites other than mastodon.social, for example. Autocompleting or drop-down-completing common social network kinds there might help with data regularity, too.

**Comment by wlonk** [comment]
Be sure also to include Ravelry! Its omission was an oversight.
