### ISSUE TITLE
Several Icon Types Not Appearing

### ISSUE THREAD

**Issue by kahomono** [wlonk/wheretofind.me#171]
At least: Diaspora*, Discord, Stackoverflow
![NoIcons](https://user-images.githubusercontent.com/20188009/120885342-67230480-c5b6-11eb-817d-590783095bd4.png)
Screenshot taken on Debian system with Firefox 78.11.0esr

**Comment by wlonk** [comment]
Looks like the ForkAwesome icons have broken. Still investigating why.

**Comment by kahomono** [comment]
bump.  no change.

**Comment by wlonk** [comment]
Hey, I know it's yonks later, but I think this has been fixed! Lemme know if it works for you, but I'm closing this for now. Thanks for the report!
