### ISSUE TITLE
Please add the ability to delete your account

### ISSUE THREAD

**Issue by ADHDefy** [wlonk/wheretofind.me#212]
I think this is a pretty important privacy feature, and it would be great to see it. :)

**Comment by ojacobson** [comment]
Thanks for your feedback!

We meant to address this in [the terms](https://wheretofind.me/tos/), along with our handling of abuse. However, it really is a separate issue that deserves its own section and probably a clearer process. We'll work on that. To be clear, we are absolutely happy to help people leave the service or delete their accounts, at any time. It's a critical privacy feature and a basic way to respect user consent.

If you'd like to delete your account, please follow the process from the terms.
