### ISSUE TITLE
Add "human name" field and search?

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#32]
Josh thinks that being able to find people you know on this could be useful. I think if we add search we have to add privacy controls, at the least to keep your page unlisted.

**Comment by wlonk** [comment]
Not just a human name, but a list of aliases; this could be used for topics, too. So Josh might list "Lovecraftesque" among his identities.

**Comment by wlonk** [comment]
Also, a "keep me unlisted" checkbox that defaults to checked will suffice as privacy controls.

**Comment by wlonk** [comment]
Also, this strongly militates for a redone non-jQuery frontend.

**Comment by ojacobson** [comment]
> Also, a "keep me unlisted" checkbox that defaults to checked will suffice as privacy controls.

Maybe reverse the sense of this sentence: "Make me searchable" and default to off.

**Comment by wlonk** [comment]
Add ability to flag one of these aliases as "preferred", and it'll show up as your in-text username everywhere on the site.

**Comment by ojacobson** [comment]
The first one, perhaps?

**Comment by wlonk** [comment]
OK, so, punchlist:
 - [ ] Add Alias model
 - [ ] Make an Alias per-user on user creation
 - [ ] Make a data migration to add initial aliases to all users
 - [ ] Make an Alias CRUD endpoint, with reordering
 - [ ] Make a UI that allows CRUDing and reordering Aliases
 - [ ] Make the UI convey that you will be referred to on-site by your first Alias
 - [ ] Make a helper method on User for "display name" that pulls from first Alias, ensure it's used everywhere.
 - [ ] Make a checkbox on the user that defaults to unchecked and that says, when checked, "Include me in search results"
 - [ ] Make a search view that searches included users' aliases.
