### ISSUE TITLE
Add blog for service updates

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#36]
Probably hosted on medium, available at a subdomain?

**Comment by wlonk** [comment]
I do think it's important that it be on other infra, to ease reporting on outages etc.

**Comment by ojacobson** [comment]
Yeah, definitely. Having it hosted on the same app or even the same platform makes it antiresilient, and likely to be unavailable at a number of points when it might be particularly relevant.

**Comment by wlonk** [comment]
It's on Mastodon now: https://mastodon.transneptune.net/@wheretofindme
