### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#48]
- Word choice everywhere
 - Communicating the D&D reordering of entries
 - Other?

**Comment by AlanDeSmet** [comment]
The color scheme is very low contrast. The Location entries are 1.97:1. The Web Content Accessibility Guidelines 2 recommend at least 4.5:1 for body text, and ideally at least 7:1 for AAA accessibility.

**Comment by AlanDeSmet** [comment]
I used http://wave.webaim.org/report#/https://wheretofind.me/@AlanDeSmet to get the contrast ratios. Click the "Contrast" button on the right to see the list. Click on the red "ABC" buttons to highlight specific areas and see the contrast listed on the bottom left.

**Comment by AlanDeSmet** [comment]
Aaaand, I now see that #43 is probably the right place for my comments. Sorry!

**Comment by wlonk** [comment]
@AlanDeSmet Yeah, this should be on #43, but thank you anyway! I actually have a better color scheme that addresses this incoming from @mirisuzanne, who did our logo, when she has the time to put it together.
