### ISSUE TITLE
Make blocks keyboard-sortable and communicate that they are draggable

### ISSUE THREAD

**Issue by phrakture** [wlonk/wheretofind.me#49]
Sorting by dragging would be wonderful - also ensure a keyboard only variant for sorting (probably a menu with "Move Up" and "Move Down")

**Comment by wlonk** [comment]
@phrakture they actually are, currently, draggable, but there's some UX work to do to communicate that. I don't know how to approach keyboard-only sorting, but I like your suggestion.

I'm gonna rename this to reflect that that is the feature needed.

**Comment by wlonk** [comment]
See also #81.

**Comment by wlonk** [comment]
See also #43.

**Comment by wlonk** [comment]
All that remains on this is to make drag and drop work with keyboard-only interaction. See https://www.barrierbreak.com/2018/10/17/can-drag-and-drop-be-made-accessible-yes-it-can-be-in-different-ways/

SortableJS doesn't give us this, unfortunately. I think we need to make the cards themselves tabindexed, and then add a few keyboard events (space to pick up or drop, arrow keys to adjust position).

**Comment by toBeOfUse** [comment]
This is now closable
