### ISSUE TITLE
Set links to open with target="_blank"

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#59]
Though consider factors like this: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by wlonk** [comment]
There's a part of me that's like, but people can open things in tabs on their own, so maybe don't force it on them… I dunno. Still considering the utility of this feature.

**Comment by wlonk** [comment]
Inclining towards Chris Coyier's opinions here: https://css-tricks.com/use-target_blank/

That all says "don't do this".

**Comment by ojacobson** [comment]
Given the prevalence of cmd-click/middle-click for tabbed browsing, hold-to-open-in-a-new-tab on mobile, and other standard user gestures for getting this on demand, I'm inclined to not do this. The linked articles are also convincing to me.
