### ISSUE TITLE
Make usernames case-insentive

### ISSUE THREAD

**Issue by wlonk** [wlonk/wheretofind.me#79]
See also #64.

If someone goes to https://wheretofind.me/@Kit it should work as well as https://wheretofind.me/@kit.

**Comment by wlonk** [comment]
Signups are now case-insensitive, all that remains is to make user-lookup case-insensitive.

**Comment by ojacobson** [comment]
Two follow-on questions:

1. Collation-insensitive?

2. Ambiguous-glyph insensitive?

**Comment by wlonk** [comment]
1. What would that mean?
2. Yes, django-registration was [already handling](https://django-registration.readthedocs.io/en/3.0/validators.html#protecting-against-homograph-attacks) that.
